name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file ./speedtest/Dockerfile --platform linux/amd64 --tag github.com/westonbelk/containers/speedtest-cli:$(date +%s) .
